name: Notify Teams on Release Merge

on:
  push:
    branches:
      - releases

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Send notification to MS Teams
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          TITLE="📦🎉 New version of Compass-DS has been released! 🚀📦"
          TEXT="✨ **Version**: \`v$VERSION\`\n\n🔍 [View commit](${{ github.event.head_commit.url }}) 🔗\n\n📥 *Install it:*\n\@hstpathways/compass-ds@$VERSION\"

          echo $TITLE
          echo $TEXT
